### ISSUE TITLE
W.I.P. or ready to deploy

### ISSUE THREAD

**Issue by gummigroda** [Azure/enterprise-azure-policy-as-code#163]
Hi, 

Thanks for the great initiative! Looks awesome 🙌

How's the status of this repo? I started to read up on how to deploy this yesterday, but got surprised that the documentation had changed in `main` today... and referring to non existing functions in the new module.

How should I go about to deploy this solution as there seems to be a ongoing transfer to a new version?
Should I wait a couple of days, or is there a stable branch I can use today?

Thanks!

**Comment by techlake** [comment]
We unfortunately had to merge the experimental stuff into main for technical reasons. Please grab the latest release 6.3.2 instead of the main head.

**Comment by techlake** [comment]
@anwather : Should they wait a couple of days?

**Comment by anwather** [comment]
@gummigroda You can use the PowerShell module if you want - it should be ok, I'll continue to update documentation today to make sure that usage is included.
```
Install-Module EnterprisePolicyAsCode
```
Most functionality will be exactly the same - for the main functions see some usage updates below

Build-DeploymentPlans - use the ```-outputFolder``` parameter to save output (otherwise it generates in the module folder)
Deploy-PolicyPlan and Deploy-RolesPlan - use the ```-inputFolder``` parameter when running these and provide location of output folder from Build-DeploymentPlans

**Comment by anwather** [comment]
I'll fix this in about 30 mins for you

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________

**Comment by anwather** [comment]
@gummigroda please run ```Update-Module EnterprisePolicyAsCode``` - should be working now

**Comment by anwather** [comment]
Awaiting author reponse

**Comment by gummigroda** [comment]
@anwather Yes, now it works. Thanks!
