### ISSUE TITLE
deploymentRootScope / Search-AzGraph Issue

### ISSUE THREAD

**Issue by glsutter** [Azure/enterprise-azure-policy-as-code#247]
I'm getting an error in Helpers/Search-AzGraphAllItem when I run Build-DeploymentPlans.ps1:
$result = Search-AzGraph $query -First 1000 @scope
                                                                               ~~~~~-
A parameter cannot be found that matches parameter name 'ManagementGroup'.

If I login using the tenant id, then run Build-DeploymentPlans.ps1, I get a similar error:
$result = Search-AzGraph $query -First 1000 @scope
                                                                               ~~~~~~
A parameter cannot be found that matches parameter name 'UseTenantScope'

Not sure, but I'm guessing the root cause is the deploymentRootScope setting in global-settings.json. Can someone tell me what I'm incorrectly setting?

Here's the relevant part of global-settings.json under "pacEnvironments":
		{
			"pacSelector": "epac-dev",
			"cloud": "AzureCloud",
			"tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
			"deploymentRootScope": "/providers/Microsoft.Management/managementGroups/EPAC-Dev"
		}

And in Azure, this is the relevant part of the MG tree:

Tenant Root Group
--> EPAC-Dev

And I run Build-DeploymentPlans.ps1 like this:
./Build-DeploymentPlans.ps1 -pacEnvironmentSelector "epac-dev"

**Comment by anwather** [comment]
Please make sure you have the latest version of Az.ResourceGraph module installed.

Which version do you have now?

Get Outlook for Android<https://aka.ms/AAb9ysg>
________________________________
From: glsutter ***@***.***>
Sent: Saturday, May 20, 2023 4:27:49 AM
To: Azure/enterprise-azure-policy-as-code ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [Azure/enterprise-azure-policy-as-code] deploymentRootScope Issues (Issue #247)


I'm getting an error in Helpers/Search-AzGraphAllItem when I run Build-DeploymentPlans.ps1:
$result = Search-AzGraph $query -First 1000 @scope<https://github.com/scope>
~~~~~-
A parameter cannot be found that matches parameter name 'ManagementGroup'.

If I login using the tenant id, then run Build-DeploymentPlans.ps1, I get a similar error:
$result = Search-AzGraph $query -First 1000 @scope<https://github.com/scope>
~~~~~~
A parameter cannot be found that matches parameter name 'UseTenantScope'

Not sure, but I'm guessing the root cause is the deploymentRootScope setting in global-settings.json. Can someone tell me what I'm incorrectly setting?

Here's the relevant part of global-settings.json under "pacEnvironments":
{
"pacSelector": "epac-dev",
"cloud": "AzureCloud",
"tenantId": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx",
"deploymentRootScope": "/providers/Microsoft.Management/managementGroups/EPAC-Dev"
}

And in Azure, this is the relevant part of the MG tree:

Tenant Root Group

EPAC-Dev

And I run Build-DeploymentPlans.ps1 like this:
./Build-DeploymentPlans.ps1 -pacEnvironmentSelector "epac-dev"

**Comment by glsutter** [comment]
That was the problem. I had to uninstall / reinstall PowerShell and all the Az modules. Not it's working. Thanks.
