### ISSUE TITLE
Question about versioning 

### ISSUE THREAD

**Issue by haflidif** [Azure/enterprise-azure-policy-as-code#75]
How would one introduce versioning to the framework of Definitions, Assignments, and initiatives?

**Comment by techlake** [comment]
Since you are using a sorce code repository as the source, it would contain the version history.

If you're asking, how can I tell in Azure what version something was built-on: one could add a version to the metadata (all Azure Policy objects have a metadata element (JSON based)).

The version metadata could be auto injected from the script. This is not currently a capability.

**Comment by techlake** [comment]
Since you are using a source code repository as the source, it would contain the version history.

If you're asking, how can I tell in Azure what version something was built-on: one could add a version to the metadata (all Azure Policy objects have a metadata element (JSON based)).

The version metadata could be auto injected from the script.

**Comment by haflidif** [comment]
Yeah I was maybe asking more about telling and recording what version something was built-on like if we have a policy that had v.1.0 then it would be changed or modified with new features etc, and then it would be v.2.0, we could then gradually move over to that policy instead of all assignments, or initiatives that have this policy would use the new version right away.

**Comment by techlake** [comment]
I would avoid that pattern, especially for built-ins (they fix bugs when creating an updated version). Locking in a specific Version would require a Policy engine change.
