### ISSUE TITLE
global-settings.jsonc pacOwnerId applies to all pacEnvironments

### ISSUE THREAD

**Issue by nicholaslanger** [Azure/enterprise-azure-policy-as-code#790]
Hi EPAC folks,

My team is facing an issue with how global-settings.jsonc defines PacOwnerId. We have a multi tenant / environment deployment strategy when using EPAC and wish to have a different PacOwnerId defined for each environment. How do you suggest we accomplish this? The current schema of global-settings.jsonc does not allow for it.

Let us know what you think! Thanks

**Comment by anwather** [comment]
I'm curious as to why you need this and how you have defined your global-settings.jsonc - for multi tenant there should be no issues with using the same owner Id, similar with same repo/different environments. If you have multiple teams managing policy the guidance is to use multiple repositories with `desiredState` set to `ownedOnly` - then they can use different PacOwnerId's

**Comment by nicholaslanger** [comment]
We were under the impression that pacOwnerId must be associated with a service principal id as the docs state the recommended format is a GUID. Does it really matter what id pacOwnerId is? Is the recommended approach to create different branches for each deployment of EPAC to each of our scopes in which global settings is different? can it be as arbitrary as string of our teams name? We were able to run plan successfully using the string of our team name.

**Comment by anwather** [comment]
PacOwnerId can be any string - it is used in the case of multiple teams running different EPAC projects. EPAC will never remove any policy that has a different PacOwnerId. For instance say you have a security team who deploy policies using EPAC and then a platform team doing the same, having different owner Id's means they can deploy at the same root deployment scope and not effect each others work. 

For an example see https://azure.github.io/enterprise-azure-policy-as-code/settings-desired-state/#use-case-3-multiple-teams-with-shared-responsibility

We only recommend a GUID because there are heaps of them - but any string is acceptable

**Comment by anwather** [comment]
Close due to no response - please re-open if you need anything!
